ATOMS = "Bi" "Te"
DIM = 3 3 2
BAND = 0 0 0  0.5 0 0  0.3333 0.3333 0  0 0 0 
BAND_LABELS = $\Gamma$ M K $\Gamma$ 
BAND_POINTS = 51
MP = 11 11 11
EIGENVECTORS = .TRUE.
FC_SYMMETRY = .TRUE.
SYMPREC = 1.0e-5
FULL_FORCE_CONSTANTS = .TRUE.
FORCE_CONSTANTS = WRITE
GROUP_VELOCITY = .TRUE.
